### ISSUE TITLE
Awesome project! Care to add a LICENSE.txt?

### ISSUE THREAD

**Issue by andrewperry** [matthaywardwebdesign/aus-search#2]
Thanks for sharing this and the great post at https://hackernoon.com/open-data-node-js-elasticsearch-13-million-street-addresses-and-counting-7a20f14e006f

It would be great for you to add a LICENSE.txt so it is clear on what basis you are sharing it - MIT / BSD?

**Comment by matthaywardwebdesign** [comment]
Thanks @andrewperry! :)

Whoops! Forgot to add that one, adding now (MIT)

**Comment by andrewperry** [comment]
Nice - thanks!
