### ISSUE TITLE
Latest GNAF in download.sh

### ISSUE THREAD

**Issue by SmileSydney** [matthaywardwebdesign/aus-search#6]
In `download.sh` you link to `wget -O ./data/gnaf-latest.zip https://data.gov.au/dataset/19432f89-dc3a-4ef3-b943-5326ef1dbecc/resource/4b084096-65e4-4c8e-abbe-5e54ff85f42f/download/may18gnafpipeseparatedvalue20180521161504.zip`

Just wondering if this is correct - I note the latest might be (note may19): https://data.gov.au/data/dataset/19432f89-dc3a-4ef3-b943-5326ef1dbecc/resource/4b084096-65e4-4c8e-abbe-5e54ff85f42f/download/may19_gnaf_pipeseparatedvalue_20190521155815.zip

**Comment by matthaywardwebdesign** [comment]
Hey! A PR was just submitted to update this to the latest dataset :)
