### ISSUE TITLE
elasticsearch-import.js error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SmileSydney** [matthaywardwebdesign/aus-search#7]
Hi @matthaywardwebdesign thanks for sharing this.

All the prior steps worked fine up to and including simplify and create elastic index. Any ideas?

`node elasticsearch-import.js
`
```
/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^
RangeError: Maximum call stack size exceeded

```

**Comment by SmileSydney** [comment]
I reduced the batch count in `elasticsearch-import.js` from 1,000 to 500 and now seems to load ok

**Comment by carneeki** [comment]
I got it to work by increasing the stack size when starting:

```
node --stack-size=16000 elasticsearch-import.js
Connected to MongoDB server
...`
