### ISSUE TITLE
Simplify imports only 9k AddressSimple records

### ISSUE THREAD

**Issue by carneeki** [matthaywardwebdesign/aus-search#8]
Running `node simplify.js`reports "Finished simplifying addressDetail" but only 9101 AddressSimple records are created.

This results in a very small percentage of records being pushed into elastic.

Also of interested is
* 54mins (real time) to create 10k AddressSimple records compared to 44mins to import all the addressDetail records
* Record count is updated line-by-line rather than every 10k records.

Environment:
Running in WSL (Ubuntu 16.04 inside Windows 10)
```
$ node --version
v10.15.3
$
```

**Comment by carneeki** [comment]
Looking through the typescript output I see `MongoError: cursor id 13454509178 not found`
A cursory search indicates this might be timeout related. https://stackoverflow.com/questions/46423442/mongodb-cursor-not-found

I'm going to try adding a `.noCursorTimeout()` and seeing if this imports everything.

**Comment by carneeki** [comment]
Other advice in https://stackoverflow.com/questions/44248108/mongodb-error-getmore-command-failed-cursor-not-found recommends reducing the batch size. I tried a batch size of 1000 and it seems to be running, and maybe a bit faster too; but that's subjective.

Will report back shortly. It could be that on smaller systems, 10k is a bit too big.

**Comment by carneeki** [comment]
`simplify.js` is about halfway through the addresses now, I'm going to let it run overnight.

It feels like it's taking a lot longer than it should, but it could be VM overhead. I don't have a baseline for comparison.

**Comment by akhiakl** [comment]
Is your error fixed?
If yes can you update the codes you changed here? I am getting same error while simplifying addressDetails collection.

**Comment by carneeki** [comment]
From memory, I wound up increasing the stack size to 16000 and no code changes were necessary.

**Comment by akhiakl** [comment]
I had done that but still no change. This error popped up one day, before that it was working fine.

**Comment by carneeki** [comment]
I remember there was a 10k batch size somewhere, do a search for 10000 and
experiment with reducing the batch size maybe?

I think node might hit a memory limit and fails if the batch is too large.

**Comment by matthaywardwebdesign** [comment]
@carneeki Yeah I think one of the main reasons imports take a while is due to the way the data is being structured internally as it is being imported. I should probably look at improving that process. I would also recommend reducing the batch size, the amount of memory you have on your machine will determine what the ideal batch size should be.
